sudo: required
services:
- docker
env:
  global:
  - secure: iq4nqhC46FukpmYTSn+SoCIfHRSbrC3fk4Bu8G34TL14g2lvHMkjltE2d/yyazlJd2J8cUHPQQ3XFK4nH7fEctOp3kdR21QkgsX3WfsTnPVjlN1sU3+xOcpGm6pUT6VOmOVFkg8V1CeUd1Xn8yiJqMWkHizsoGkDq/m9bIPnX4db0Hbx/+HFl8IuWeM/xaXINUo0tbKR7WLBSwG44teHh7AbveOB556HJhUNCRI4JU2i3TGuADjAWrcHFrgrZz9mX1w7U/d3mp6Ru0j6q5q/LAXmRxvd+3HkXuUwWE5kZvr1ISLgtPrYE1roXdWk2YD+uCmr3rqZXJA8pAh/JjfaXlek1aRj15YdMu6UDBFtrk+b7sLzndfiXXrCLIJvrfYy0qnu6EKXcivtFusZ9MtP/+NB/wVBLo/V0pEeWR3O6O9JhD+4ijsgEz/w9pyB3IIlx0yqu9qVrqo33Z8Zn2LHwM6LDqNUWLH/aMqTcdYJEmsUZ3Cl75uzSoR/aFtcbfUcV3MkuC4afApMaF79iiAXaLdYgvza07QRV2qjtOdwqw/Q4k42QFWqC6AVFY7Ab/qpI92D/n60a6h6gpzDfoBBA706cn81peyIMzxtga98PuHJDulfsCJ2R5p9s+zT2zKeRQDHvHTVoR4UwoMDv6sbsFPYT5EBlcPyF3ZAfXNtPTE=
  - secure: DPnb7XsLYrgks7rwU05dUTD7yGsDdLw7PPU+qEv8ZPSjLKaGzX01B02HNc/jv7xTsAbgvLNUBeKh/7RBWXBWU4nWtu9+OMR8c5X3YBmiuTEdihXhWy8E/m+MjMr5chjrUaKVWmP/Hj6vXN5+K6k1Wi4RDjC4fp4/pTgmUXzcRiskQn1txRDsf8MiBZYc4iO7uf+BdA0nPo4wLKSmU/jCvZ6WdLeqEPvCUFAIKecZ3AWBF1muUWxTSrpQUF2HyHtmpUgsEXRXzdfz2oEL1rYBrn5DwAF4uSj+FdwG0DTt3nYfO52QImcATUg6tjQ0rxfNiaRrx/OBpwBXG7lpJwV0dbUffdCdjR1POlh3Ihwec+ZOG/HFkVWuRFxs50kIuEbyCn2Z/YVzeNDNzkOQ4SllXm4P3r6UwLsb2lzsYkij8Gs5DQBZV6ihu/Kc33r8hbgTtPmvz6K+FhjuJZy3MOo9UwlMqmMrq7/MczmipD65FJjVG8O5ycoA8h34jb9oS6ygj0ag307BqpJGEzgwmn5JvgoZ0yM90a4A7pFMAMRcBYLzm3rdCEvGe7NXhjc5pcI4m5t2SybypLGnwtaxF3rA7xOtyyKjY2ljGeknaIpe5ELY4z1K4inQzpj0iSoU25hAscHmwWgPWnYMHnQ/PxpiMbIwbU1TzqnEtVWX3zx4GnU=
before_script:
- docker pull nutthapat1423/stock-frontend || true
script:
- docker build --pull --cache-from nutthapat1423/stock-frontend  --tag nutthapat1423/stock-frontend  .
after_script:
- docker images
before_deploy:
- docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS}
deploy:
  - provider: script
    script: docker push nutthapat1423/stock-frontend
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: bPeC4LvmSEfJHCDhvp9JJ2hOjTNymcWB+usqfDUV8ilGBGFIbOEF/xEl3BBqM92aL6l60MJS9vRDK9DvjDcJe/XhrF8B0SXs99KO6SQElFkujymTTbjyTn4HM1PPVL1quML2F9IiU0d8y4HBH+6+IdmCh6CJhnVz8jKivX7+XsjhNr4T9E+de3qCF9tErlkNNq866JAJj6jCSOiLkBZnHPxvtF7MSdUHWWrMdMO8Tu+nmA7hWDKY/3SP6EY4a27bQQC1u8ckIqOaOKmuUXzM2ERHF1P/Xn0WUE7TL6Vmfsmpk995egDq83iEqI7wB9v0w3lwzei0aAiHkop4mXosYVD7Hy4+eBgQSlKmTm7KqkjiiTPHfSlXL4frIGxhLjpJ90bopJWQrdZOSa/XMDzNId0+E9uXUs4VBLfKZInU9rEPypmOW1D11wABvkcW399pluuueLL5dby1QyswkzTWqfHEsw3OPF7hvrtf+k85Ia9vcnIuu4b8OrzQMVzpO7BER8ZVELVikRUHqJK9ZWKVTdSd1/3eWsjcpRUlUyxQV19BCg9p4ggm7kodEenV8kEebCyLzPVyu2rXFARXskxKwvPIITIuTFwxMNUp+MK/lZV7ZNqRPb3obC7uFgWZQ5KkozqBW3WMccec1hXgmTNb4tQUWZtzlvH+6+lzVh6zoek=
    app: stock-frontend