sudo: required
language: python
python:
  - 3.8
install: pip install -r requirements.txt
script:
  - echo "skipping tests"
deploy:
  provider: heroku
  app: stock-frontend
  on:
    branch: master
  api_key:
    secure: H6iXd1jVCSrnTt3E5H0jZFTqd/y4hP+4IEdTHtPGU0LQtwxRqVsRsNWg8jln+aXi6ygmafwaHQSAvGKK9WUSjbmMq1V9wtfyogD+Y+9WXmlgtfqGYtctk1sk3aE0/qd/fuSiXfXVlh3XYElDk94FqA66B9Rx9oIcXNv77L0gMbdeBQbKtlcGv2p31XElKRIsup5vaJKDKmpkrW8lJzF5Lw8wEUbe/d0RJpPhe61tKQnDJ2rvnChjJASMsc4oeKU7UGoqDZwsIhfPIqpcjvAnmRPfPXMbSISF576n1mDCdJfdv7KYkpCvNv3rAV9OaB1qIrOd1fL+jDYZxqfdZ+YZqiCb7IO+67pOfi3jhuQA0DZOz5EWlmxd0bY/smHw49jRGT4C3hZM/vscYly5Duzw5p8Q0zAId6Cu6v+7MHclmNzdBsVBx1IdEbtaheHjCCkVQ15kCgdEo3YwWT79lNoX1LTPBwTw0Cx9xBwZ9aH6ubmhVYEP+wj6tUuejJABEzAov/riPBv5MqPVkMaDgRHhUO1m/2LGdmuVJ/A/kqdpkunTSnFvLSPi9IZ5xDksaZa7gMoXhZLfzydL785rgoftID7fZKXzhmMONujJs0PeqnSkjs28w3Yu8QRYr3sI2SybdpOq2SxXVnqwuvtbtKfyaUfztV8M+DFiO5kQrD+vqww=
