sudo: required
language: python
python:
- 3.8
install: pip install -r requirements.txt
script:
- echo "skipping tests"
deploy:
  provider: heroku
  app: stock-frontend
  on:
    branch: master
  api_key:
    secure: pH0RP9rI1wLrNAsNfCr+PLLSDsR8TcWC8nZPniBvyLA81wYrK10x0e3WtW3hj2PnkcBmwcNDGKNZeZ4jWbAdRwYfLIu+/FGOgko3eL55kn3XFlzUiW1rRVPDjSBIv3iJHEMb9UJsOHqDEXLuipgN5T0WWQn4iLXYIe/cnmcUxONyiG+G/unxoPv9Jhc0KkvAxtsLYYji6oPrJXs+LBSUvaELXzwpjpPJ08L5+n6ZjVXiWR0WAo3bAsKTFQOrwpNgbDVvvye5CBkWmB7AUr+jvL2euCt9dNlSK5Q6/hCRjP7LKFhjxQr43nv3ru42SCAL3Nn43VPA0Q8MmMoC3lEA1UgsVaWoPiYr2HdI+V8HI5IrzTMqs9+dZOkqEG+yGvgHVA+W60L+Xexhpp8zB/zAI2tdcHtqQOsGpygmFGO1kFXBAxhoixbYSAcwUoYG82nzH6CVfYGsNM0KCro94ElB3nMSPM7CCl3xM+1lOJwY6ghqh8DZUd3Hxf1cLQHji4FU+zELXbkVP/CuI5eSchRQ7HlWxwn8E4L9AlRvUci6Ml9fVgKTFGnbq0LDOGe0ZtjfPqrNzamLx027/08XTF0uEwE0IfXg5f0LhjOyrAFpE8pA5yjSdUqjcTAzDbPRqysgKuZqPEyximPS+miaI7oYthZTxXOgLLMEIP2+FWE3lOM=
  skip_cleanup: true 